import type { Conversation, Memory, Alert, AgentLog, DebateStage, ActionPlan } from "@/types/business-memory"

export const mockUser = {
  id: "1",
  name: "سارا احمدی",
  role: "مدیرعامل",
  avatar: "/professional-woman-avatar.png",
  company: {
    name: "تجارت پردیس",
    industry: "تجارت الکترونیک",
    size: 15,
    founded: 1398,
  },
  preferences: ["تحلیل داده‌محور", "گزارش‌های مختصر", "تمرکز بر ROI"],
}

export const mockConversations: Conversation[] = [
  {
    id: "1",
    title: "توسعه به دبی",
    lastMessage: "تحلیل بازار دبی تکمیل شد",
    date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    messageCount: 12,
    isActive: true,
    type: "debate",
  },
  {
    id: "2",
    title: "استخدام مدیر فروش",
    lastMessage: "سه کاندیدای نهایی معرفی شدند",
    date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    messageCount: 8,
    isActive: false,
    type: "simple",
  },
  {
    id: "3",
    title: "کاهش هزینه‌ها",
    lastMessage: "برنامه صرفه‌جویی تصویب شد",
    date: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000),
    messageCount: 15,
    isActive: false,
    type: "debate",
    completed: true,
  },
]

export const mockMemories: Memory[] = [
  {
    id: "1",
    type: "decision",
    title: "تصمیم: توسعه به دبی",
    content: "تصمیم گرفته شد که شعبه دبی با بودجه ۵۰۰ هزار دلار راه‌اندازی شود. نتیجه: ۲ مشتری بزرگ جذب شد.",
    date: new Date(Date.now() - 6 * 30 * 24 * 60 * 60 * 1000),
    result: "success",
    relevanceScore: 95,
    isActive: false,
  },
  {
    id: "2",
    type: "meeting",
    title: "جلسه با سرمایه‌گذار",
    content: "جلسه با صندوق سرمایه‌گذاری الف. پیشنهاد ۲ میلیون دلار با ۱۵٪ سهام.",
    date: new Date(Date.now() - 2 * 30 * 24 * 60 * 60 * 1000),
    relevanceScore: 78,
    isActive: false,
  },
  {
    id: "3",
    type: "insight",
    title: "تحلیل رقبا",
    content: "رقیب اصلی قیمت‌ها را ۱۰٪ افزایش داد. فرصت برای جذب مشتری.",
    date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    relevanceScore: 88,
    isActive: true,
  },
]

export const mockAlerts: Alert[] = [
  {
    id: "1",
    priority: "high",
    title: "مهلت تمدید قرارداد",
    description: "قرارداد با شرکت تأمین‌کننده اصلی تا ۵ روز دیگر منقضی می‌شود.",
    confidence: 100,
    date: new Date(),
    icon: "alert-triangle",
  },
  {
    id: "2",
    priority: "medium",
    title: "فرصت: رقیب قیمت را افزایش داد",
    description: "شرکت رقیب قیمت‌ها را ۱۰٪ افزایش داده. فرصت مناسب برای جذب مشتری.",
    confidence: 85,
    date: new Date(Date.now() - 2 * 60 * 60 * 1000),
    icon: "trending-up",
  },
]

export const mockAgentLogs: Record<string, AgentLog[]> = {
  analyst: [
    { time: 0.2, message: "دریافت اطلاعات ورودی", status: "complete" },
    { time: 0.5, message: "جستجوی وب: بازار دبی", status: "complete", detail: "یافتن ۵ منبع" },
    { time: 1.2, message: "محاسبه ROI...", status: "complete", detail: "Model: excel formula" },
    { time: 2.1, message: "نوشتن تحلیل...", status: "complete", progress: 84 },
    { time: 3.5, message: "تحلیل کامل", status: "complete" },
  ],
  strategist: [
    { time: 0.3, message: "بارگذاری context", status: "complete" },
    { time: 0.8, message: "تولید سناریوها...", status: "complete" },
    { time: 1.5, message: "بررسی فرصت‌ها", status: "complete" },
    { time: 2.8, message: "Extended thinking mode ON", status: "complete" },
    { time: 4.2, message: "۳ سناریو آماده", status: "complete" },
  ],
  critic: [
    { time: 0.4, message: "شروع تحلیل ریسک", status: "complete" },
    { time: 1.1, message: "شناسایی خطرات...", status: "complete" },
    { time: 1.9, message: "ساخت ماتریس ریسک", status: "complete" },
    { time: 3.2, message: "راهکارهای کاهش", status: "complete" },
    { time: 4.5, message: "تحلیل ریسک کامل", status: "complete" },
  ],
}

export const mockDebateStages: DebateStage[] = [
  {
    id: "query-analysis",
    title: "درک سؤال شما...",
    icon: "search",
    status: "complete",
    time: 0.8,
    items: [
      { label: "متن دریافت شد", done: true },
      { label: "زبان: فارسی", done: true },
      { label: "موضوع: تصمیم استراتژیک", done: true },
      { label: "پیچیدگی: بالا", done: true },
      { label: "تأثیر مالی: >۵۰ هزار دلار", done: true },
      { label: "مسیر: مشاوره استراتژیک", done: true, isRoute: true },
    ],
  },
  {
    id: "memory-retrieval",
    title: "جستجوی حافظه شرکت...",
    icon: "brain",
    status: "complete",
    time: 0.3,
    searchStatus: "۱۲۳ نتیجه یافت شد",
    memories: mockMemories.slice(0, 3),
    tokenCount: 2150,
  },
  {
    id: "agent-activation",
    title: "فعال‌سازی ۳ تحلیلگر تخصصی",
    icon: "bot",
    status: "complete",
    agents: [
      {
        id: "analyst",
        name: "تحلیلگر داده‌محور",
        model: "GPT-4o",
        icon: "bar-chart",
        color: "analyst",
        status: "complete",
        confidence: 85,
        logs: mockAgentLogs.analyst,
      },
      {
        id: "strategist",
        name: "استراتژیست خلاق",
        model: "Gemini 3 Pro",
        icon: "lightbulb",
        color: "strategist",
        status: "complete",
        confidence: 78,
        logs: mockAgentLogs.strategist,
        scenarios: [
          { type: "pessimistic", label: "بدبینانه" },
          { type: "realistic", label: "واقع‌بینانه" },
          { type: "optimistic", label: "خوش‌بینانه" },
        ],
      },
      {
        id: "critic",
        name: "تحلیلگر ریسک",
        model: "Grok-2",
        icon: "alert-triangle",
        color: "critic",
        status: "complete",
        confidence: 92,
        logs: mockAgentLogs.critic,
      },
    ],
  },
  {
    id: "confidence-calibration",
    title: "هماهنگی نمایندگان...",
    icon: "scale",
    status: "complete",
    consensus: 72,
    needsSecondRound: true,
    matrix: [
      [100, 75, 68],
      [75, 100, 70],
      [68, 70, 100],
    ],
  },
  {
    id: "synthesis",
    title: "داور نهایی (Claude Opus 4.5)",
    icon: "gavel",
    status: "complete",
    time: 5.2,
    synthesisLogs: [
      { time: 0.5, message: "دریافت ۳ تحلیل" },
      { time: 1.2, message: "مقایسه دیدگاه‌ها..." },
      { time: 2.1, message: "یافتن نقاط مشترک" },
      { time: 3.8, message: "تولید طرح‌های عملی...", progress: 62 },
      { time: 5.2, message: "تصمیم نهایی آماده" },
    ],
    summary:
      "با توجه به تحلیل‌های سه‌گانه، توسعه به دبی در سال ۱۴۰۴ توصیه می‌شود. بهترین استراتژی، شروع با دفتر نمایندگی کوچک و توسعه تدریجی است.",
    metaConfidence: 88,
  },
]

export const mockActionPlans: ActionPlan[] = [
  {
    id: "conservative",
    title: "محافظه‌کارانه",
    icon: "shield",
    successRate: 90,
    timeline: "۳ ماه",
    budget: "۵۰ میلیون تومان",
    riskLevel: "low",
    recommended: true,
    steps: [
      "تحقیق بازار محلی دبی",
      "استخدام مشاور بومی",
      "راه‌اندازی دفتر نمایندگی کوچک",
      "جذب ۲ مشتری آزمایشی",
      "ارزیابی نتایج پس از ۳ ماه",
    ],
    resources: ["بودجه اولیه: ۵۰ میلیون تومان", "نیروی انسانی: ۲ نفر", "زمان مدیریت: ۱۰ ساعت/هفته"],
    assumptions: ["نرخ ارز ثابت می‌ماند", "روابط تجاری ایران-امارات پایدار است", "تقاضا برای محصول وجود دارد"],
  },
  {
    id: "balanced",
    title: "متعادل",
    icon: "scale",
    successRate: 70,
    timeline: "۶ ماه",
    budget: "۱۵۰ میلیون تومان",
    riskLevel: "medium",
    steps: [
      "تأسیس شرکت در منطقه آزاد",
      "استخدام تیم ۵ نفره",
      "راه‌اندازی فروشگاه آنلاین",
      "کمپین بازاریابی دیجیتال",
      "شراکت با ۳ توزیع‌کننده محلی",
      "رسیدن به نقطه سربه‌سر",
    ],
    resources: ["بودجه: ۱۵۰ میلیون تومان", "تیم: ۵ نفر", "زمان: ۲۰ ساعت/هفته"],
    assumptions: ["بازار رقابتی اما قابل نفوذ", "امکان جذب استعداد محلی", "زیرساخت لجستیکی مناسب"],
  },
  {
    id: "aggressive",
    title: "تهاجمی",
    icon: "rocket",
    successRate: 50,
    timeline: "۱۲ ماه",
    budget: "۵۰۰ میلیون تومان",
    riskLevel: "high",
    steps: [
      "افتتاح دفتر مرکزی در دبی",
      "استخدام تیم ۱۵ نفره",
      "راه‌اندازی خط تولید محلی",
      "حضور در ۳ نمایشگاه بین‌المللی",
      "جذب سرمایه‌گذار محلی",
      "توسعه به کشورهای همسایه",
    ],
    resources: ["بودجه: ۵۰۰ میلیون تومان", "تیم: ۱۵ نفر", "زمان: تمام‌وقت"],
    assumptions: ["دسترسی به سرمایه کافی", "توانایی رقابت با برندهای بزرگ", "ثبات سیاسی منطقه"],
  },
]

export const mockStats = {
  totalConversations: 234,
  totalDebates: 45,
  decisionsTracked: 123,
  successRate: 85,
  rlImprovement: 28,
  averageResponseTime: 8.3,
  npsScore: 72,
  thumbsUpRatio: 85,
  memorySize: 2.3 * 1024 * 1024 * 1024,
  lastBackup: new Date(Date.now() - 5 * 60 * 1000),
  systemAccuracy: 87,
  accuracyChange: 2,
}
